### ISSUE TITLE
!ready command

### ISSUE THREAD

**Issue by Marcedarc** [Komeran/avina#2]
### `!ready` command

Command to mark yourself as ready for a game.

For DMs and players: `!ready <game>` where <game> is the name of a game on this server.

#### Expected behaviour:
1. Check syntax
2. Check if server has games
3. Check if game exists
4. Check if user is DM of the game
4.1 If yes, set `game.dmReady = true` and proceed to 6.
4.2 If no, check if user is a player of the game
5. If yes, set `player.ready = true`
6. Check if user is player in different games
6.1 If yes, set `player.ready = false` for those games
7. Send message to the user that he is marked unready for the other games.
8. Send message to command channel that the player/DM is ready

### `!unready` command

Command to mark yourself as unready for all games of this server.

For DMs and players: `!unready`

#### Expected behaviour:
1. Check syntax
2. Check if server has games
3. For all games of server
3.1 Check if user is DM of the game
3.1.1 If yes, set `game.dmReady = false`
3.2 Check if user is a player of the game
3.2.1 If yes, set `player.ready = false`
4. Send message to the user that he is now marked unready in all games

### Tasks:

- [ ] Implement `!ready` command
- [ ] Implement `!unready` command
- [ ] Update dependent commands
  - [ ] `!draw`
  - [ ] `!quests` (Fall back to readied game as default)
